name: Sync
on:
  schedule:
    - cron: "0 1-10 * * 1-5"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.G_TOKEN }}
      - name: Rebase
        run: |
          git remote add upstream https://github.com/linglongdev/Repository-Manager.git
          git fetch upstream
          git rebase -Xtheirs upstream/main
          git push origin main --force
