name: Sync
on:
  schedule:
    - cron: "0 1-10 * * 1-5"
  workflow_dispatch:
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 2
          token: ${{ secrets.G_TOKEN }}
      - name: Rebase
        run: |
          git config --global user.name "inf-sup"
          git config --global user.email "174466778+inf-sup@users.noreply.github.com"
          git remote add upstream https://github.com/linglongdev/Repository-Manager.git
          git fetch upstream
          diff=$(git diff origin/main upstream/main --numstat -- ':!repos.yaml' ':!history')
          if [ -n "$diff" ]; then
            echo -e "find differences:\n$diff"
            message=$(git log -n 1 --pretty=format:"%s%n%b")
            git reset --soft HEAD^
            git checkout upstream/main -- . ":(exclude)repos.yaml"
            git commit -m "$message"
            git rebase -Xtheirs upstream/main
            git push origin main --force
          else
            echo "no differences"
          fi
